# Generated by Django 6.0.2 on 2026-04-24 11:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comments", "0001_initial"),
        ("posts", "0002_search_trigger"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("harassment", "Harassment"),
                            ("hate_speech", "Hate Speech"),
                            ("abuse", "Abuse"),
                            ("explicit_content", "Explicit Content"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("details", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reviewed", "Reviewed"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "reported_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="comments.comment",
                    ),
                ),
                (
                    "reported_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="posts.post",
                    ),
                ),
                (
                    "reported_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="common_reports_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="common_reports_filed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("reported_comment__isnull", True),
                                ("reported_post__isnull", True),
                                ("reported_user__isnull", False),
                            ),
                            models.Q(
                                ("reported_comment__isnull", True),
                                ("reported_post__isnull", False),
                                ("reported_user__isnull", True),
                            ),
                            models.Q(
                                ("reported_comment__isnull", False),
                                ("reported_post__isnull", True),
                                ("reported_user__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="report_exactly_one_target",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("reported_user__isnull", False)),
                        fields=("reporter", "reported_user"),
                        name="unique_report_per_user",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("reported_post__isnull", False)),
                        fields=("reporter", "reported_post"),
                        name="unique_report_per_post",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("reported_comment__isnull", False)),
                        fields=("reporter", "reported_comment"),
                        name="unique_report_per_comment",
                    ),
                ],
            },
        ),
    ]
