# Generated by Django 6.0.2 on 2026-03-11 15:04

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                (
                    "username",
                    models.CharField(db_index=True, max_length=30, unique=True),
                ),
                ("first_name", models.CharField(blank=True, max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional name shown on profile; falls back to username.",
                        max_length=60,
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=500)),
                ("website", models.URLField(blank=True)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Profile picture — wired to media app in M3.",
                        null=True,
                        upload_to="avatars/",
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "pronouns",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("he/him", "He/Him"),
                            ("she/her", "She/Her"),
                            ("they/them", "They/Them"),
                            ("he/they", "He/They"),
                            ("she/they", "She/They"),
                            ("any", "Any pronouns"),
                            ("ask me", "Ask me"),
                            ("prefer_not", "Prefer not to say"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "pronouns_custom",
                    models.CharField(
                        blank=True,
                        help_text="Used when pronouns=CUSTOM.",
                        max_length=50,
                    ),
                ),
                (
                    "pronouns_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Everyone"),
                            ("followers", "Followers only"),
                            ("only_me", "Only me"),
                        ],
                        default="public",
                        max_length=10,
                    ),
                ),
                (
                    "gender_identity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("man", "Man"),
                            ("woman", "Woman"),
                            ("non_binary", "Non-binary"),
                            ("genderqueer", "Genderqueer"),
                            ("genderfluid", "Genderfluid"),
                            ("agender", "Agender"),
                            ("bigender", "Bigender"),
                            ("transgender", "Transgender"),
                            ("two_spirit", "Two-Spirit"),
                            ("questioning", "Questioning"),
                            ("prefer_not", "Prefer not to say"),
                            ("custom", "Custom (see bio)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "gender_identity_custom",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "gender_identity_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Everyone"),
                            ("followers", "Followers only"),
                            ("only_me", "Only me"),
                        ],
                        default="followers",
                        max_length=10,
                    ),
                ),
                (
                    "sexual_orientation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("gay", "Gay"),
                            ("lesbian", "Lesbian"),
                            ("bisexual", "Bisexual"),
                            ("pansexual", "Pansexual"),
                            ("queer", "Queer"),
                            ("asexual", "Asexual"),
                            ("aromantic", "Aromantic"),
                            ("demisexual", "Demisexual"),
                            ("straight", "Straight/Heterosexual"),
                            ("questioning", "Questioning"),
                            ("prefer_not", "Prefer not to say"),
                            ("custom", "Custom (see bio)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "sexual_orientation_custom",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "sexual_orientation_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Everyone"),
                            ("followers", "Followers only"),
                            ("only_me", "Only me"),
                        ],
                        default="only_me",
                        max_length=10,
                    ),
                ),
                (
                    "account_privacy",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("followers_only", "Followers only"),
                            ("private", "Private"),
                        ],
                        default="followers_only",
                        max_length=15,
                    ),
                ),
                (
                    "safe_messaging_mode",
                    models.BooleanField(
                        default=True,
                        help_text="Blur images from non-followers; require follow before DM.",
                    ),
                ),
                (
                    "location_sharing",
                    models.BooleanField(
                        default=False,
                        help_text="Opt-in only — never shared by default.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "is_verified",
                    models.BooleanField(default=False, help_text="Email verified."),
                ),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users_user",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="BlockedUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blocked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_by_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "blocker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocking_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "users_blocked",
            },
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="accepted",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "following",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follower_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "users_follow",
            },
        ),
        migrations.CreateModel(
            name="MutedUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "muted",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="muted_by_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "muter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="muting_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "users_muted",
            },
        ),
        migrations.CreateModel(
            name="UserReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("hate_speech", "Hate speech / homophobia / transphobia"),
                            ("harassment", "Harassment or bullying"),
                            ("spam", "Spam"),
                            ("impersonation", "Impersonation"),
                            ("outing", "Outing someone without consent"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("details", models.TextField(blank=True, max_length=1000)),
                ("reviewed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reported",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_filed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "users_report",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_user_email_6f2530_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["username"], name="users_user_usernam_65d164_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active", "date_joined"],
                name="users_user_is_acti_b9727e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="blockeduser",
            index=models.Index(
                fields=["blocker"], name="users_block_blocker_6e8fa4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blockeduser",
            index=models.Index(
                fields=["blocked"], name="users_block_blocked_37dd3c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="blockeduser",
            unique_together={("blocker", "blocked")},
        ),
        migrations.AddIndex(
            model_name="follow",
            index=models.Index(
                fields=["follower", "status"], name="users_follo_followe_bab817_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="follow",
            index=models.Index(
                fields=["following", "status"], name="users_follo_followi_e1f61e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together={("follower", "following")},
        ),
        migrations.AlterUniqueTogether(
            name="muteduser",
            unique_together={("muter", "muted")},
        ),
        migrations.AddIndex(
            model_name="userreport",
            index=models.Index(
                fields=["reported", "reviewed"], name="users_repor_reporte_c35294_idx"
            ),
        ),
    ]
