# Generated by Django 6.0.2 on 2026-03-20 13:32

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("posts", "0002_search_trigger"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(max_length=1000)),
                (
                    "depth",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="0 = top-level, 1 = reply, 2 = reply-to-reply. Max 2.",
                    ),
                ),
                ("is_hidden", models.BooleanField(default=False)),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_flagged", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for top-level comments; set for replies.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="comments.comment",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="posts.post",
                    ),
                ),
            ],
            options={
                "db_table": "comments_comment",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["post", "parent", "is_deleted"],
                        name="comments_co_post_id_27e9c4_idx",
                    ),
                    models.Index(
                        fields=["post", "is_pinned", "created_at"],
                        name="comments_co_post_id_da1c6a_idx",
                    ),
                ],
            },
        ),
    ]
