# Generated by Django 6.0.2 on 2026-03-20 11:12

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("posts", "0002_search_trigger"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("post_id", models.UUIDField(db_index=True)),
                (
                    "score",
                    models.FloatField(
                        default=0.0,
                        help_text="Pre-computed ranking score. Higher = shown earlier.",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("follow", "Followed user's post"),
                            ("hashtag", "Subscribed hashtag"),
                            ("explore", "Explore / recommended"),
                        ],
                        default="follow",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user whose feed this item belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "feed_item",
                "ordering": ["-score", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "score"], name="feed_item_user_id_7bcee2_idx"
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="feed_item_user_id_c04a0b_idx",
                    ),
                ],
                "unique_together": {("user", "post_id")},
            },
        ),
        migrations.CreateModel(
            name="HashtagSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hashtag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscribers",
                        to="posts.hashtag",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hashtag_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "feed_hashtag_subscription",
                "unique_together": {("user", "hashtag")},
            },
        ),
    ]
